### ISSUE TITLE
Change Popup design for Dark mode 

### ISSUE THREAD

**Issue by Kedar-K** [HemendraKhatik/Memory-Game#15]
Tasks:

- [x] Change the design of popup to a dark theme when the user switches the dark mode on.

- [x] Increase the contrast of the `ok` button in the popup

![Memory-Game](https://user-images.githubusercontent.com/25702901/94802161-c8ca1800-0404-11eb-8962-23dd9e8f5fe3.png)

**Comment by yoBoyio** [comment]
Hello @Kedar-K  could I work on this?

**Comment by Kedar-K** [comment]
@yoBoyio Sure you can, Read the instructions in readme.md before you start tough

**Comment by Kedar-K** [comment]
Good one @yoBoyio
